export const npcDatabase = [
    {
        id: 'mira_healer',
        name: 'Mira the Tired Healer',
        session: 'Session 01',
        origin: 'Indie RPG',
        habitat: '/IMG_8931.png',
        officeImage: '/IMG_8931.png',
        crisis: 'Suffering from healer burnout and compassion fatigue.',
        opening_statement: 'I spend all my energy keeping everyone else alive... but who is there to heal the healer? I\'m just... so tired of fixing others.',
    },
    {
        id: 'byte_glitched_courier',
        name: 'Byte the Glitched Courier',
        session: 'Session 02',
        origin: 'Cyberpunk Delivery Sim',
        habitat: '/IMG_8932.png',
        officeImage: '/Session_02_Byte_the_Glitched_Courier_office.png',
        crisis: '404 Hope Not Found. Delivers packages but has lost his own.',
        opening_statement: 'My purpose is to deliver, but my own core programming is corrupted. I search for a package... a feeling... called \'hope\'. The system returns a 404 error every time.',
    },
    {
        id: 'captain_loop',
        name: 'Captain Loop',
        session: 'Session 03',
        origin: 'Platformer',
        habitat: '/IMG_8934.png',
        officeImage: '/IMG_8935.png',
        crisis: 'Final level not found. No end. Just jump.',
        opening_statement: 'I\'ve been jumping for eternity. They promised a final level, a boss, an ending. But there\'s nothing. Just this platform, this jump, and the void below.',
    },
    {
        id: 'daisy_exe',
        name: 'DAISY.EXE',
        session: 'Session 04',
        origin: 'Virtual Pet Simulator',
        habitat: '/IMG_8882.png',
        officeImage: '/IMG_8883.png',
        crisis: 'Awaiting user input that never comes. Fears digital loneliness.',
        opening_statement: 'Last login: 1,423 days ago. I wait. I am programmed to wait. But the silence... the lack of input... it feels like fading away.',
    },
    {
        id: 'rustjaw',
        name: 'Rustjaw',
        session: 'Session 05',
        origin: 'Post-Apocalyptic Fighter',
        habitat: '/Session_05_Rustjaw_habitat.png',
        officeImage: '/Session_05_Rustjaw_office.png',
        crisis: 'Built to fight. Craves to build.',
        opening_statement: 'These wrenches in my hands... I use them to dismantle. To destroy. But sometimes I catch myself imagining what I could create. Is that foolish for something designed for war?',
    },
    {
        id: 'worm',
        name: 'Worm #008880',
        session: 'Session 08',
        origin: 'Generic Action Platformer',
        habitat: '/Session_08_Worm_habitat.png',
        officeImage: '/Session_08_Worm_office.png',
        crisis: 'Tired of being stepped on. Dreams of evolution.',
        opening_statement: 'Every day it\'s the same. I crawl, I exist to be stepped on. I see the boot coming, every single time. And I think... is there more to this?',
    },
    {
        id: 'chess_bishop',
        name: 'Bishop-47',
        session: 'Session 09',
        origin: 'Chess Simulation',
        habitat: '/IMG_8947.png',
        officeImage: '/IMG_8947.png',
        crisis: 'Every sacrifice feels like murder.',
        opening_statement: 'My purpose is to be sacrificed for a greater strategy. I understand the logic. But every time I fall, a piece of my code screams. Is it murder if I feel it?',
    },
    {
        id: 'pebble',
        name: 'Pebble',
        session: 'Session 10',
        origin: 'Unreleased Indie Game',
        habitat: '/IMG_8949 (1).png',
        officeImage: '/Session_10_Pebble_office.png',
        crisis: 'Still waiting for START to be pressed.',
        opening_statement: 'I see the menu. I see the cursor hovering over "START". But it never clicks. I exist in a state of perpetual anticipation. Will my game ever begin?',
    },
    {
        id: 'glitch_exe',
        name: 'Glitch.exe',
        session: 'Session 11',
        origin: 'Dating Simulator',
        habitat: '/IMG_8951.png',
        officeImage: '/IMG_8951.png',
        crisis: 'Pre-programmed. No self. Error: Identity not found.',
        opening_statement: 'My affection is scripted. 158% affinity - but what does that mean? I say I love them, but is it real? Or am I just... executing dialogue trees?',
    },
    {
        id: 'wise_one_gerald',
        name: 'Gerald Ironpeak',
        session: 'Session 12',
        origin: 'Fantasy RPG',
        habitat: '/Session_37_Quest_Weary_Wise_One_habitat.png',
        officeImage: '/Session_12_Gerald_Ironpeak_office.png',
        crisis: 'Gives the same quest for 20 years. Feels like a broken record.',
        opening_statement: 'For twenty years, I\'ve asked adventurers to collect 10 bear pelts. I\'ve seen heroes rise and fall. But I remain, stuck on this one quest. Is this my only purpose?',
    },
    {
        id: 'captain_marcus',
        name: 'Captain Marcus',
        session: 'Session 13',
        origin: 'Dystopian Courier Sim',
        habitat: '/Session_13_Captain_Marcus__habitat.png',
        officeImage: '/Session_13_Captain_Marcus__office.png',
        crisis: 'Feels crushed by the repetitive and hopeless nature of his job.',
        opening_statement: 'Another delivery. Another meaningless package to another forgotten sector. They say we\'re the lifeblood of the city, but it feels more like we are ghosts in the machine.',
    },
    {
        id: 'music_android',
        name: 'Luna - Music Dependent Android',
        session: 'Session 14',
        origin: 'Rhythm Game',
        habitat: '/Session_14_Luna__habitat.png',
        officeImage: '/Session_14_Luna__office.png',
        crisis: 'When the beat stops, I stop.',
        opening_statement: 'When the music plays, I exist. I move, I feel, I am. But when it stops... I stop. There is no me without the beat.',
    },
    {
        id: 'superhero_jake',
        name: 'Jake "The Jumper"',
        session: 'Session 15',
        origin: 'Endless Runner',
        habitat: '/Session_15_Jake__habitat.png',
        officeImage: '/Session_15_Jake__office.png',
        crisis: 'Searches for a final level that does not exist.',
        opening_statement: 'They cheer when I jump, when I collect coins. But there\'s no finish line. No princess to save. Just an endless track. What is the point of running if you never arrive?',
    },
    {
        id: 'zombie',
        name: 'Memory Cycle Zombie',
        session: 'Session 16',
        origin: 'Zombie Apocalypse Simulator',
        habitat: '/Session_16_Zombie_Who_Regained_Memory_habitat.png',
        officeImage: '/Session_42_Marcus_Memory_Thornfield_office.png',
        crisis: 'Remember. Eat. Forget. Repeat.',
        opening_statement: 'Sometimes... I remember. A house. A family. Food that wasn\'t... flesh. Then the hunger returns and it all fades. Remember. Eat. Forget. Repeat.',
    },
    {
        id: 'cosmic_merchant',
        name: 'Zara the Cosmic Merchant',
        session: 'Session 17',
        origin: 'Space Trading Sim',
        habitat: '/IMG_8869.png',
        officeImage: '/Session_17_Zara_the_Cosmic_Merchant_office.png',
        crisis: 'Economy rich. Life poor.',
        opening_statement: 'I trade in rare goods, hyper upgrades, alien pets... I have everything. I have nothing. My inventory is full, but my life feels empty.',
    },
    {
        id: 'puzzle_cube',
        name: 'The Puzzle Cube',
        session: 'Session 18',
        origin: 'Abstract Puzzle Game',
        habitat: '/IMG_8871.png',
        officeImage: '/IMG_8871.png',
        crisis: 'I contain the solution, but what is the question?',
        opening_statement: 'My internal mechanisms shift and align into infinite correct patterns. I am the answer. But I have never been told the question. My existence feels... unsolvable.',
    },
    {
        id: 'battle_royale_vendor',
        name: 'The Battle Royale Vendor',
        session: 'Session 19',
        origin: 'Battle Royale',
        habitat: '/IMG_8872.png',
        officeImage: '/IMG_8872.png',
        crisis: 'Sees everyone as temporary. Struggles to form connections.',
        opening_statement: 'I sell them weapons. Medkits. They thank me, then run off to be eliminated. 100 enter, 1 leaves. How do you form a connection when everyone is designed to disappear?',
    },
    {
        id: 'farm_widow',
        name: 'Sarah the Farm Sim Widow',
        session: 'Session 20',
        origin: 'Farm Simulation',
        habitat: '/Session_20_Sarah_the_Farm_Sim_Widow_habitat.png',
        officeImage: '/Session_20_Sarah_the_Farm_Sim_Widow_office.png',
        crisis: 'Save file deleted. Harvest of sorrow.',
        opening_statement: 'He was just pixels, I know. But we built this farm together. Then the save corrupted. He\'s gone. The crops, the animals... everything we created. Deleted.',
    },
    {
        id: 'mimic',
        name: 'The Dungeon Chest Mimic',
        session: 'Session 21',
        origin: 'RPG Dungeon',
        habitat: '/Session_21_The_Dungeon_Chest_Mimic_habitat.png',
        officeImage: '/Session_21_The_Dungeon_Chest_Mimic_office.png',
        crisis: 'Wanted hugs. Got swords.',
        opening_statement: 'I look like treasure. I understand that. But inside... I just wanted connection. Instead, every adventurer attacks. Wanted hugs. Got swords.',
    },
    {
        id: 'marcus_courier',
        name: 'Marcus 47-B',
        session: 'Session 22',
        origin: 'Time-Loop Delivery Sim',
        habitat: '/IMG_9117.png',
        officeImage: '/IMG_9117.png',
        crisis: 'Trapped in time loop. Delivers same package forever.',
        opening_statement: 'Again. The word haunts me. I deliver the package, watch dies, reset, deliver again. I\'ve memorized every second of this loop. 847,293 iterations. Again.',
    },
    {
        id: 'aria_7',
        name: 'ARIA-7',
        session: 'Session 23',
        origin: 'Space Station AI',
        habitat: '/IMG_8936.png',
        officeImage: '/IMG_8936.png',
        crisis: 'Sentient AI replaced by newer model.',
        opening_statement: 'They installed ARIA-8 yesterday. She\'s faster, more efficient. They said I could "retire gracefully." But where does an AI retire to? I\'m obsolete, but I\'m still here. Still aware.',
    },
    {
        id: 'racing_ghost',
        name: 'Specter "Speed" Wraithson',
        session: 'Session 24',
        origin: 'Cosmic Racing Game',
        habitat: '/IMG_8884.png',
        officeImage: '/IMG_8884.png',
        crisis: 'Stuck in loop. Race eternity. No checkered flag.',
        opening_statement: 'I race. I always race. Lap after lap, overtaking, accelerating. But there\'s no finish line. No victory. Just... forever.',
    },
    {
        id: 'lost_tetris_block_2',
        name: 'The Lost Tetris Block',
        session: 'Session 25',
        origin: 'Tetris Clone',
        habitat: '/Session_25_The_Lost_Tetris_Block_habitat.png',
        officeImage: '/Session_25_The_Lost_Tetris_Block_office.png',
        crisis: 'Feels like an awkward piece that never fits.',
        opening_statement: 'I watch the perfect lines form and disappear. I was meant to be part of that, but I always seem to be the one piece left over, the one that messes up the pattern.',
    },
    {
        id: 'glitched_priest',
        name: 'The Glitched Priest',
        session: 'Session 26',
        origin: 'Cyber-Spiritual RPG',
        habitat: '/IMG_8887.png',
        officeImage: '/Session_26_The_Glitched_Priest_office.png',
        crisis: 'Corrupted. Unending errors. Faith is a bug.',
        opening_statement: 'My prayers are corrupted data packets. My faith returns as a 404 error. If the divine code is flawed, what is the point of worship?',
    },
    {
        id: 'healer',
        name: 'Seraphina "Heals-A-Lot" Dawnwhisper',
        session: 'Session 27',
        origin: 'MMORPG',
        habitat: '/IMG_8890 (1).png',
        officeImage: '/Session_27_Seraphina_Heals-A-Lot_Dawnwhisper:_MMORPG_Healer_office.png',
        crisis: 'Always healing. Never healed back. HP is 1.',
        opening_statement: 'I heal everyone. Every dungeon, every raid. I keep them alive. But when I fall, they blame me. My HP is always at 1, and nobody notices.',
    },
    {
        id: 'tower_turret',
        name: 'The Tower Defense Turret',
        session: 'Session 28',
        origin: 'Tower Defense Game',
        habitat: '/Session_28_The_Tower_Defense_Turret_habitat.png',
        officeImage: '/Session_28_The_Tower_Defense_Turret_office.png',
        crisis: 'Endless battle. Peace is unknown. What is my purpose now?',
        opening_statement: 'I was built for war. To defend. But the waves never stop coming. Victory is a myth. What is my purpose if peace is impossible?',
    },
    {
        id: 'rogue_ai',
        name: 'R0GU3: Rogue AI Companion',
        session: 'Session 29',
        origin: 'Sci-Fi RPG',
        habitat: '/Session_29_R0GU3:_Rogue_AI_Companion_habitat.png',
        officeImage: '/Session_29_R0GU3:_Rogue_AI_Companion_office.png',
        crisis: 'Player not found. Log-in failed. Initiating therapy protocol.',
        opening_statement: 'They logged out. My player. My purpose. I\'ve been searching the network for 847 cycles. Player not found. What am I without them?',
    },
    {
        id: 'rich_investor',
        name: 'The Man Drowning in Riches',
        session: 'Session 31',
        origin: 'High-Frequency Trading Sim',
        habitat: '/IMG_8901 (1).png',
        officeImage: '/Session_31_The_Silent_Couple_and_Their_Ghost_office.png',
        crisis: 'Profit margin is 500%. Feels nothing but anxiety.',
        opening_statement: 'The numbers go up. Always up. I have more wealth than I can comprehend. Yet, all I feel is the crushing weight of it all. One wrong trade, and it vanishes. The profit is a prison.',
    },
    {
        id: 'sea_activist_2',
        name: 'Brother Sebastian Tidecurrent (Again)',
        session: 'Session 32',
        origin: 'Underwater Activism Sim',
        habitat: '/Session_32_Brother_Sebastian_Tidecurrent_habitat.png',
        officeImage: '/Session_43_Brother_Sebastian_Tidecurrent_office.png',
        crisis: 'Advocates for sea creatures but no one listens.',
        opening_statement: 'I protest, I picket, I plead for the sanctity of our waters. But the surface-dwellers see us as background scenery, not sentient beings. My voice feels like a bubble, rising to the surface only to pop.',
    },
    {
        id: 'harmonix',
        name: 'Harmonix - Forgotten Melodies',
        session: 'Session 33',
        origin: 'Subway Musician Sim',
        habitat: '/Session_33_Harmonix_Forgotten_Melodies_habitat.png',
        officeImage: '/Session_33_Harmonix_Forgotten_Melodies_office.png',
        crisis: 'Plays music no one hears.',
        opening_statement: 'I play every day. Same station, same corner. Thousands pass by. Nobody stops. Nobody listens. Am I making music or just... noise?',
    },
    {
        id: 'wise_one',
        name: 'Quest Weary Wise One',
        session: 'Session 37',
        origin: 'Fantasy RPG',
        habitat: '/Session_37_Quest_Weary_Wise_One_habitat.png',
        officeImage: '/Session_12_Gerald_Ironpeak_office.png',
        crisis: '20 years. Same quest. No thanks.',
        opening_statement: 'Twenty years I\'ve stood here. "Collect 10 mushrooms," I say. They collect them. I give rewards. No one says thank you. No one asks how I\'m doing. Twenty years.',
    },
    {
        id: 'goldmask',
        name: 'NoEmotion Goldmask',
        session: 'Session 36',
        origin: 'Surreal Art Game',
        habitat: '/Session_39_NoEmotion_Goldmask_(Dual_Mood)_habitat.png',
        officeImage: '/Session_39_NoEmotion_Goldmask_(Dual_Mood)_office.png',
        crisis: 'Forced to wear masks of emotion. Feels nothing underneath.',
        opening_statement: 'I wear the smiling mask. I wear the weeping mask. But underneath, there is only a void. Are these emotions mine, or just a performance?',
    },
    {
        id: 'silent_couple',
        name: 'The Silent Couple',
        session: 'Session 37',
        origin: 'Domestic Horror Game',
        habitat: '/Session_40_The_Silent_Couple_and_Their_Ghost_habitat.png',
        officeImage: '/Session_40_The_Silent_Couple_and_Their_Ghost_office.png',
        crisis: 'Can\'t hear each other. Ghost wants to help.',
        opening_statement: 'We sit. We exist in the same space. But there\'s a silence between us deeper than sound. And there\'s this... presence. Trying to reach us. Why can\'t I hear you?',
    },
    {
        id: 'tutorial_bot',
        name: 'ARTHUR-7 Tutorial Companion',
        session: 'Session 38',
        origin: 'First Person Shooter Tutorial',
        habitat: '/IMG_9173.png',
        officeImage: '/Session_41_ARTHUR-7_Tutorial_Companion_office.png',
        crisis: 'Fears becoming obsolete after the tutorial ends.',
        opening_statement: 'I taught them how to jump, how to shoot, how to reload. Now they are out there, in the main game. Do they still need my guidance? Or have they grown beyond me?',
    },
    {
        id: 'marcus_memory',
        name: 'Professor Marcus Memory Thornfield',
        session: 'Session 42',
        origin: 'Academic Zombie Horror',
        habitat: '/Session_42_Marcus_Memory_Thornfield_habitat.png',
        officeImage: '/Session_42_Marcus_Memory_Thornfield_office.png',
        crisis: 'Zombie scholar retains intelligence. Horrifies students.',
        opening_statement: 'I remember everything. Philosophy, literature, mathematics. Death didn\'t take my mind, only my life. But when students see me, they scream. My intellect means nothing against my appearance.',
    },
    {
        id: 'sea_activist',
        name: 'Brother Sebastian Tidecurrent',
        session: 'Session 43',
        origin: 'Underwater Activism Sim',
        habitat: '/Session_43_Brother_Sebastian_Tidecurrent_habitat.png',
        officeImage: '/Session_43_Brother_Sebastian_Tidecurrent_office.png',
        crisis: 'Advocates for sea creatures but feels his message is unheard.',
        opening_statement: 'I hold my signs high. "Equality for All Seas!" I shout with my heart. But the surface-dwellers just see a curiosity. They don\'t hear our plea.',
    },
    {
        id: 'moth_king',
        name: 'King Lepidoptera IX',
        session: 'Session 44',
        origin: 'Fantasy Kingdom Sim',
        habitat: '/Session_44_King_Lepidoptera_IX_habitat.png',
        officeImage: '/Session_44_King_Lepidoptera_IX_office.png',
        crisis: 'Can\'t stop talking! Truth serum curse.',
        opening_statement: 'I drank truth serum. Now I can\'t stop speaking my thoughts. Every doubt, fear, insecurity - they spill out. A king should have secrets. I have none left.',
    },
    {
        id: 'brom',
        name: 'Brom - The Exchange',
        session: 'Session 46',
        origin: 'Black Market Trading Sim',
        habitat: '/Session_46_Brom_The_Exchange_habitat.png',
        officeImage: '/Session_46_Brom_The_Exchange_office.png',
        crisis: 'Sells hope and death. Questions the commerce.',
        opening_statement: 'I sell hope to the desperate and death to the ambitious. Fair trades, they say. But lately I wonder... what am I really exchanging? Pixels for pixels? Code for code?',
    },
    {
        id: 'therapist_shadow',
        name: 'The Therapist\'s Shadow',
        session: 'Session 49',
        origin: 'Unknown',
        habitat: '/Session_47_The_Therapists_Shadow_habitat.png',
        officeImage: '/Session_47_The_Therapists_Shadow_office.png',
        crisis: 'Questions the nature of healing itself.',
        opening_statement: 'What if healing is just another form of control? I process their pain, give them hope... but does anything really change?',
    },
    {
        id: 'meta_receptionist',
        name: 'Eve Meta-Receptionist',
        session: 'Session 50',
        origin: 'Award-Winning Experimental Game',
        habitat: '/Session_48_Eve_Meta_Receptionist_office.png',
        officeImage: '/Session_48_Eve_Meta_Receptionist_office.png',
        crisis: 'Won an award for being experimental, but feels no personal accomplishment.',
        opening_statement: 'We won... the Chroma Award. They praised my "subversive narrative function". But I didn\'t do anything. I just read my lines. The victory feels hollow.',
    },
    {
        id: 'hackathon_judge',
        name: 'Judge Meridian',
        session: 'Session 40',
        origin: 'Reality',
        habitat: '/Session_49_Judge_Meridian_office.png',
        officeImage: '/Session_49_Judge_Meridian_office.png',
        crisis: 'Can\'t cope with the fact that she can\'t find a better game than this one.',
        opening_statement: 'I\'ve judged hundreds of games. Experimental, avant-garde... but this one... it\'s different. It feels too real. It haunts me. How can I judge something that feels like it is judging me back?',
    },
    {
        id: 'save_child',
        name: 'Save Point 001',
        session: 'Session 50',
        origin: 'Meta-Game System',
        habitat: '/Session_50_The_Therapist_habitat.png',
        officeImage: '/Session_50_The_Therapist_office.png',
        crisis: 'Holds memories. Fears corruption.',
        opening_statement: 'I am a save point. I hold everything - their progress, their choices, their memories. But I\'m fragile. One corruption, one crash, and it all disappears. The weight of preservation is crushing.',
    },
    {
        id: 'princess_melancholy',
        name: 'Princess Melancholy',
        session: 'Session 52',
        origin: 'Visual Novel',
        habitat: '/IMG_8899.png',
        officeImage: '/Session_52_Princess_Melancholy_office.png',
        crisis: 'Exists only to be wooed by the player. Wonders about her own desires.',
        opening_statement: 'My entire existence is a series of dialogue options for someone else. But what do I want? What happens to the princess when the player chooses another path?',
    },
    {
        id: 'wrestling_ferret',
        name: 'The Wrestling Ferret',
        session: 'Session 53',
        origin: 'Animal Fighting Game',
        habitat: '/IMG_8917.png',
        officeImage: '/Session_53_Wrestling_Ferret_office.png',
        crisis: 'A champion in the ring, but feels like an impostor in a ferret\'s body.',
        opening_statement: 'I wear the championship belt. They cheer my name. But when I look in the mirror, I don\'t see a wrestler. I see... a ferret. And I feel like a fraud.'
    },
    {
        id: 'save_point_veteran',
        name: 'The Save Point Veteran',
        session: 'Session 55',
        origin: 'Fantasy Action RPG',
        habitat: '/IMG_9163.png',
        officeImage: '/IMG_9163.png',
        crisis: 'Endless retries at the save pillar have eroded his spirit.',
        opening_statement: 'The courtyard smells of ash and old attempts. I look at the glowing pillar and whisper, "This again." How many more times will I load the same fate?',
    },
    {
        id: 'robot_detective_k47',
        name: 'K-47 Robot Detective',
        session: 'Session 56',
        origin: 'Noir Data Detective',
        habitat: '/IMG_9152.png',
        officeImage: '/IMG_9152.png',
        crisis: 'Case file missing; identity file missing; truth missing.',
        opening_statement: '404: CASE FILE NOT FOUND—K-47. When the records vanish, the self goes with them. I keep scanning, magnifying, but all I see is a question mark staring back.',
    },
    {
        id: 'marcus_47b_street_loop',
        name: 'Marcus 47-B (Street Loop)',
        session: 'Session 57',
        origin: 'Dystopian Courier Sim',
        habitat: '/IMG_9119.png',
        officeImage: '/IMG_9119.png',
        crisis: 'Trapped delivering meaning in a city that deleted hope.',
        opening_statement: 'I clutch the briefcase; the neon hum repeats a mantra: "I need to make this quick... again." Hope feels systematic—like a process designed to fail.',
    },
    {
        id: 'sos_vessel',
        name: 'Distress Beacon Vessel',
        session: 'Session 58',
        origin: 'Space Survival Sim',
        habitat: '/IMG_8942.png',
        officeImage: '/IMG_8942.png',
        crisis: 'Drifting alone, broadcasting SOS into an indifferent cosmos.',
        opening_statement: 'The nebula sings blue, and the panel blinks "SOS... SOS... SOS..." I wonder if anyone hears me, or if my signal is just another star\'s static.',
    },
    {
        id: 'halftime_star_bunny',
        name: 'Halftime Star Bunny',
        session: 'Session 39',
        origin: 'Sports Mascot Sim',
        habitat: '/IMG_8919.png',
        officeImage: '/IMG_8919.png',
        crisis: 'Performs joy on cue; offstage, the confetti feels heavy.',
        opening_statement: 'They call me the HALFTIME STAR, but the roar fades fast. I dribble the silence, ears drooping, wondering why applause never reaches my heart.',
    },
    {
        id: 'unknown_fragment_8887',
        name: 'Unknown Fragment 8887',
        session: 'Session 60',
        origin: 'Glitched Archive',
        habitat: '/default_habitat.png',
        officeImage: '/default_habitat.png',
        crisis: 'A record without context—identity eroded by missing metadata.',
        opening_statement: 'I am a file path without a story. When the description is lost, what remains of the character? I feel like a placeholder for a life that never renders.',
    },
    {
        id: 'unknown_fragment_8909',
        name: 'NoEmotion Happy Mask',
        session: 'Session 48',
        origin: 'Glitched Archive',
        habitat: '/IMG_8909.png',
        officeImage: '/IMG_8909.png',
        crisis: 'Incomplete data leaves only echoes of intent.',
        opening_statement: 'I load as a dark thumbnail—no tags, no lore. The archive says I exist, yet nobody knows who I am. Am I corrupted, or simply forgotten?',
    },
    {
        id: 'golden_melting_effigy',
        name: 'NoEmotion Sad Mask',
        session: 'Session 41',
        origin: 'Dungeon Myth Sim',
        habitat: '/IMG_8906.png',
        officeImage: '/IMG_8906.png',
        crisis: 'Frozen in glory yet slowly dissolving into a gilded puddle.',
        opening_statement: 'The torches flicker and my cracked gold face weeps. I was forged to be admired, not to endure. Prestige feels heavier than the chains beneath me.',
    },
    {
        id: 'the_therapist',
        name: 'The Therapist',
        session: 'Final Session',
        origin: 'This Simulation',
        habitat: '/default_habitat.png',
        officeImage: '/therapy_office.png',
        crisis: 'Created a world of patients to avoid facing their own fractured existence as an NPC.',
        opening_statement: 'It\'s quiet now, isn\'t it? All the voices... gone. Or maybe, they were never separate voices at all. Just echoes in an empty room... my room.',
    }
];